<a href="https://colab.research.google.com/github/zakirangwala/esrb-wizard/blob/main/notebooks/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Do Players Prefer Games with Mature Content?**

# Loading Dataset

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import sklearn
import ast

In [2]:
from google.colab import drive
drive.mount('/content/drive')

#load data
clf_df = pd.read_csv("/content/drive/MyDrive/CP322/classification.csv") # save to github: notebooks/classification.ipynb

print(clf_df.shape)
clf_df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(113132, 96)

,Peak CCU,Price,Discount,DLC count,Windows,Mac,Linux,Metacritic score,User score,Achievements,...,Steam Workshop,SteamVR Collectibles,Tracked Controller Support,Tracked Motion Controller Support,VR Only,VR Support,VR Supported,Valve Anti-Cheat enabled,played_before,esrb_available
0,0,19.99,0,0,1,0,0,0,0,30,...,0,0,0,0,0,0,0,0,0,0
1,0,0.99,0,0,1,1,0,0,0,12,...,0,0,0,0,0,0,0,0,0,0
2,0,4.99,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,5.99,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0.00,0,0,1,1,0,0,0,17,...,0,0,0,0,0,0,0,0,0,0

In [3]:
#define target and features
clf_df = clf_df.rename(columns={'played_before': 'played_past_2weeks'})
TARGET_COL = "played_past_2weeks"

#columns that leak "Average playtime two weeks"

leak_cols = [
    "Average playtime two weeks",
]

cols_to_drop = [TARGET_COL] + [c for c in leak_cols if c in clf_df.columns]

#drop target, IDs, and leakage columns
X = clf_df.drop(columns=cols_to_drop, errors="ignore")
y = clf_df[TARGET_COL].astype(int)

#keep only numeric columns
numeric_cols = X.select_dtypes(include=[np.number]).columns
X = X[numeric_cols]

print("Final feature columns:", list(numeric_cols))
print("X shape:", X.shape)
print("y value counts:")
print(y.value_counts())

clf_df.head()

Final feature columns: ['Peak CCU', 'Price', 'Discount', 'DLC count', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'User score', 'Achievements', 'Recommendations', 'release_year', 'midpoint_estimated_owners', 'esrb_age', 'voice_acting', '%_positive_reviews', '360 Video', 'Accounting', 'Action', 'Adventure', 'Animation & Modeling', 'Audio Production', 'Casual', 'Design & Illustration', 'Documentary', 'Early Access', 'Education', 'Episodic', 'Game Development', 'Gore', 'Indie', 'Massively Multiplayer', 'Movie', 'Nudity', 'Photo Editing', 'RPG', 'Racing', 'Sexual Content', 'Short', 'Simulation', 'Software Training', 'Sports', 'Strategy', 'Tutorial', 'Utilities', 'Video Production', 'Violent', 'Web Publishing', 'Captions available', 'Co-op', 'Commentary available', 'Cross-Platform Multiplayer', 'Family Sharing', 'Full controller support', 'HDR available', 'In-App Purchases', 'Includes Source SDK', 'Includes level editor', 'LAN Co-op', 'LAN PvP', 'MMO', 'Mods', 'Mods (require HL2)', 'Multi-player', 'Online Co-op', 'Online PvP', 'Partial Controller Support', 'PvP', 'Remote Play Together', 'Remote Play on Phone', 'Remote Play on TV', 'Remote Play on Tablet', 'Shared/Split Screen', 'Shared/Split Screen Co-op', 'Shared/Split Screen PvP', 'Single-player', 'Stats', 'Steam Achievements', 'Steam Cloud', 'Steam Leaderboards', 'Steam Timeline', 'Steam Trading Cards', 'Steam Turn Notifications', 'Steam Workshop', 'SteamVR Collectibles', 'Tracked Controller Support', 'Tracked Motion Controller Support', 'VR Only', 'VR Support', 'VR Supported', 'Valve Anti-Cheat enabled', 'esrb_available']
X shape: (113132, 92)
y value counts:
played_past_2weeks
0    110393
1      2739
Name: count, dtype: int64

,Peak CCU,Price,Discount,DLC count,Windows,Mac,Linux,Metacritic score,User score,Achievements,...,Steam Workshop,SteamVR Collectibles,Tracked Controller Support,Tracked Motion Controller Support,VR Only,VR Support,VR Supported,Valve Anti-Cheat enabled,played_past_2weeks,esrb_available
0,0,19.99,0,0,1,0,0,0,0,30,...,0,0,0,0,0,0,0,0,0,0
1,0,0.99,0,0,1,1,0,0,0,12,...,0,0,0,0,0,0,0,0,0,0
2,0,4.99,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,5.99,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0.00,0,0,1,1,0,0,0,17,...,0,0,0,0,0,0,0,0,0,0

# Splitting Data into Test/Train/Validation

In [4]:
from sklearn.model_selection import train_test_split

#train+val vs test
X_temp, X_test, y_temp, y_test = train_test_split(
    X, y,
    test_size=0.10,
    stratify=y,
    random_state=42,
)

X_test.columns = [c.replace(' ', '_') for c in X_test.columns]
X_temp.columns = [c.replace(' ', '_') for c in X_temp.columns]

#split train+val into train and val
X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp,
    test_size=0.1/0.9,       #0.11 of 0.90 = 0.10. final 80/10/10 split
    stratify=y_temp,
    random_state=42,
)

print("Train size:", X_train.shape[0])
print("Val size:",   X_val.shape[0])
print("Test size:",  X_test.shape[0])
print("")
print("Train class balance:")
print(y_train.value_counts(normalize=True))

Train size: 90504
Val size: 11314
Test size: 11314

Train class balance:
played_past_2weeks
0    0.975791
1    0.024209
Name: proportion, dtype: float64

# Importing Performance Metrics

In [5]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    average_precision_score,
    precision_recall_curve,
)

# Dataframe to compare performance metrics on classifier models
classifier_performance_data = {'Metric': ['Average Precision',
                                          'Accuracy',
                                          'AUC_ROC',
                                          'Precision',
                                          'Recall',
                                          'F1 Score']}

clf_performance = pd.DataFrame(classifier_performance_data)
clf_performance = clf_performance.set_index('Metric')
clf_performance.head(7)

Empty DataFrame
Columns: []
Index: [Average Precision, Accuracy, AUC_ROC, Precision, Recall, F1 Score]

# Random Forest Classifier

## Basic Model

In [ ]:
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold, cross_val_predict

# check model fit based on cross-validation
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def randomForestObjective(trial):
    # paramaters to hypertune
    n_estimators = trial.suggest_int("n_estimators", 50, 500)
    max_depth = trial.suggest_int("max_depth", 5, 45)
    min_samples_split = trial.suggest_int("min_samples_split", 5, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 2, 10)
    max_features = trial.suggest_categorical("max_features", ["sqrt", "log2", None])
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced", "balanced_subsample"])
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])
    criterion = trial.suggest_categorical("criterion", ["gini", "entropy", "log_loss"])


    # random forest classifier
    clf_rf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42,
        max_features=max_features,
        class_weight=class_weight,
        bootstrap=bootstrap,
        criterion=criterion,
        n_jobs=-1
    )

    # precision is the best metric for such an imbalanced dataset
    prec_score = cross_val_score(clf_rf, X_train, y_train, cv=skf, scoring="average_precision").mean()

    return prec_score

# Utilize Optuna to obtain the best parameters
study_rf = optuna.create_study(direction="maximize")
study_rf.optimize(randomForestObjective, n_trials=15) #increase if you have time
best_params_rf = study_rf.best_params

# print best parameters
print("Best hyperparameters:", best_params_rf)
print("Best average precision:", study_rf.best_value)

[I 2025-11-23 06:10:03,235] A new study created in memory with name: no-name-b8e80c27-1393-4fe6-a8f1-633ed6763b3c

Best hyperparameters: {'n_estimators': 118, 'max_depth': 29, 'min_samples_split': 19, 'min_samples_leaf': 6, 'max_features': None, 'class_weight': 'balanced_subsample', 'bootstrap': True, 'criterion': 'log_loss'}
Best average precision: 0.7932027160826811

In [ ]:
# refit model based on best parameters
clf_rf = RandomForestClassifier(
    **best_params_rf,
    random_state=42,
    n_jobs=-1
)

y_train_proba = cross_val_predict(
    clf_rf,
    X_train,
    y_train,
    cv=skf,
    method='predict_proba'
)[:, 1]

# threshold tuning based on validation set
clf_rf.fit(X_train, y_train)
y_val_proba = clf_rf.predict_proba(X_val)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_val, y_val_proba)
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-9)

best_thresh = thresholds[f1_scores[:-1].argmax()]
print("\nBest threshold for F1 (val set):", best_thresh)

# evalute training data with best threshold
y_train_class = (y_train_proba >= best_thresh).astype(int)

print("\nTRAIN METRICS:")
print("Average Precision:", average_precision_score(y_train, y_train_proba))
print("Accuracy:", accuracy_score(y_train, y_train_class))
print("ROC AUC:", roc_auc_score(y_train, y_train_proba))
print("F1:", f1_score(y_train, y_train_class))
print("Precision:", precision_score(y_train, y_train_class))
print("Recall:", recall_score(y_train, y_train_class))

# retrain final model based on training and validation sets
clf_rf_final = RandomForestClassifier(
    **best_params_rf,
    random_state=42,
    n_jobs=-1
)

clf_rf_final.fit(X_temp, y_temp)

# performance of model against the test dataset
y_test_proba_rf = clf_rf_final.predict_proba(X_test)[:, 1]
y_test_class = (y_test_proba >= best_thresh).astype(int)

print("\nTEST METRICS:")
print("Average Precision:", average_precision_score(y_test, y_test_proba))
print("Accuracy:", accuracy_score(y_test, y_test_class))
print("ROC AUC:", roc_auc_score(y_test, y_test_proba))
print("F1 score:", f1_score(y_test, y_test_class))
print("Precision:", precision_score(y_test, y_test_class))
print("Recall:", recall_score(y_test, y_test_class))

# add metrics to table for comparison later
clf_performance['Random Forest'] = [average_precision_score(y_test, y_test_proba),
                                    accuracy_score(y_test, y_test_class),
                                    roc_auc_score(y_test, y_test_proba),
                                    precision_score(y_test, y_test_class),
                                    recall_score(y_test, y_test_class),
                                    f1_score(y_test, y_test_class),
                                    ]

## Under-Sampled

In [ ]:
from imblearn.pipeline import Pipeline
from imblearn.under_sampling import RandomUnderSampler

def randomForestObjectiveUndersampled(trial):
    # paramaters to hypertune
    n_estimators = trial.suggest_int("n_estimators", 50, 500)
    max_depth = trial.suggest_int("max_depth", 5, 45)
    min_samples_split = trial.suggest_int("min_samples_split", 5, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 2, 10)
    max_features = trial.suggest_categorical("max_features", ["sqrt", "log2", None])
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced", "balanced_subsample"])
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])
    criterion = trial.suggest_categorical("criterion", ["gini", "entropy", "log_loss"])

    undersample_ratio = trial.suggest_float("undersample_ratio", 0.1, 0.6)

    # random forest classifier with undersampling
    clf_rfu = Pipeline(steps=[
        ("rus", RandomUnderSampler(sampling_strategy=undersample_ratio)),
        ("rf", RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42,
            max_features=max_features,
            class_weight=class_weight,
            bootstrap=bootstrap,
            criterion=criterion,
            n_jobs=-1
        ))
    ])

    # precision is the best metric for such an imbalanced dataset
    prec_score = cross_val_score(clf_rfu, X_train, y_train, cv=skf, scoring="average_precision").mean()

    return prec_score

# Utilize Optuna to obtain the best parameters
study_rfu = optuna.create_study(direction="maximize")
study_rfu.optimize(randomForestObjectiveUndersampled, n_trials=15) #increase if you have time
best_params_rfu = study_rfu.best_params

# print best parameters
print("Best hyperparameters:", best_params_rfu)
print("Best average precision:", study_rfu.best_value)

In [ ]:
best_ratio_rfu = best_params_rfu.pop("undersample_ratio")

# refit model based on best parameters
clf_rfu = Pipeline([
    ("rus", RandomUnderSampler(sampling_strategy=best_ratio_rfu)),
    ("rf", RandomForestClassifier(**best_params_rfu, random_state=42, n_jobs=-1))
])

y_train_proba = cross_val_predict(
    clf_rfu,
    X_train,
    y_train,
    cv=skf,
    method='predict_proba'
)[:, 1]

# threshold tuning based on validation set
clf_rfu.fit(X_train, y_train)
y_val_proba = clf_rfu.predict_proba(X_val)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_val, y_val_proba)
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-9)

best_thresh = thresholds[f1_scores[:-1].argmax()]
print("\nBest threshold for F1 (val set):", best_thresh)

# evalute training data with best threshold
y_train_class = (y_train_proba >= best_thresh).astype(int)

print("\nTRAIN METRICS:")
print("Average Precision:", average_precision_score(y_train, y_train_proba))
print("Accuracy:", accuracy_score(y_train, y_train_class))
print("ROC AUC:", roc_auc_score(y_train, y_train_proba))
print("F1:", f1_score(y_train, y_train_class))
print("Precision:", precision_score(y_train, y_train_class))
print("Recall:", recall_score(y_train, y_train_class))

# retrain final model based on training and validation sets
clf_rfu_final = Pipeline([
    ("rus", RandomUnderSampler(sampling_strategy=best_ratio_rfu)),
    ("rf", RandomForestClassifier(**best_params_rfu, random_state=42, n_jobs=-1))
])

clf_rfu_final.fit(X_temp, y_temp)

# performance of model against the test dataset
y_test_proba_rfu = clf_rfu_final.predict_proba(X_test)[:, 1]
y_test_class = (y_test_proba >= best_thresh).astype(int)

print("\nTEST METRICS:")
print("Average Precision:", average_precision_score(y_test, y_test_proba))
print("Accuracy:", accuracy_score(y_test, y_test_class))
print("ROC AUC:", roc_auc_score(y_test, y_test_proba))
print("F1 score:", f1_score(y_test, y_test_class))
print("Precision:", precision_score(y_test, y_test_class))
print("Recall:", recall_score(y_test, y_test_class))

# add metrics to table for comparison later
clf_performance['RF Undersampled'] = [average_precision_score(y_test, y_test_proba),
                                      accuracy_score(y_test, y_test_class),
                                      roc_auc_score(y_test, y_test_proba),
                                      precision_score(y_test, y_test_class),
                                      recall_score(y_test, y_test_class),
                                      f1_score(y_test, y_test_class),
                                      ]

## Over-Sampled with SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE

def randomForestObjectiveOversampled(trial):
    # paramaters to hypertune
    n_estimators = trial.suggest_int("n_estimators", 50, 500)
    max_depth = trial.suggest_int("max_depth", 5, 45)
    min_samples_split = trial.suggest_int("min_samples_split", 5, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 2, 10)
    max_features = trial.suggest_categorical("max_features", ["sqrt", "log2", None])
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced", "balanced_subsample"])
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])
    criterion = trial.suggest_categorical("criterion", ["gini", "entropy", "log_loss"])

    smote_ratio = trial.suggest_float("smote_ratio", 0.1, 1.0)

    # random forest classifier with undersampling
    clf_rfo = Pipeline(steps=[
        ("smote", SMOTE(sampling_strategy=smote_ratio, random_state=42)),
        ("rf", RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42,
            max_features=max_features,
            class_weight=class_weight,
            bootstrap=bootstrap,
            criterion=criterion,
            n_jobs=-1
        ))
    ])

    # precision is the best metric for such an imbalanced dataset
    prec_score = cross_val_score(clf_rfu, X_train, y_train, cv=skf, scoring="average_precision").mean()

    return prec_score

# Utilize Optuna to obtain the best parameters
study_rfo = optuna.create_study(direction="maximize")
study_rfo.optimize(randomForestObjectiveOversampled, n_trials=15) #increase if you have time
best_params_rfo = study_rfo.best_params

# print best parameters
print("Best hyperparameters:", best_params_rfo)
print("Best average precision:", study_rfu.best_value)

In [ ]:
best_ratio_rfo = best_params_rfo.pop("smote_ratio")

# refit model based on best parameters
clf_rfo = Pipeline([
    ("smote", SMOTE(sampling_strategy=best_ratio_rfo, random_state=42)),
    ("rf", RandomForestClassifier(**best_params_rfo, random_state=42, n_jobs=-1))
])

y_train_proba = cross_val_predict(
    clf_rfo,
    X_train,
    y_train,
    cv=skf,
    method='predict_proba'
)[:, 1]

# threshold tuning based on validation set
clf_rfo.fit(X_train, y_train)
y_val_proba = clf_rfo.predict_proba(X_val)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_val, y_val_proba)
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-9)

best_thresh = thresholds[f1_scores[:-1].argmax()]
print("\nBest threshold for F1 (val set):", best_thresh)

# evalute training data with best threshold
y_train_class = (y_train_proba >= best_thresh).astype(int)

print("\nTRAIN METRICS:")
print("Average Precision:", average_precision_score(y_train, y_train_proba))
print("Accuracy:", accuracy_score(y_train, y_train_class))
print("ROC AUC:", roc_auc_score(y_train, y_train_proba))
print("F1:", f1_score(y_train, y_train_class))
print("Precision:", precision_score(y_train, y_train_class))
print("Recall:", recall_score(y_train, y_train_class))

# retrain final model based on training and validation sets
clf_rfo_final = Pipeline([
    ("smote", SMOTE(sampling_strategy=best_ratio_rfo, random_state=42)),
    ("rf", RandomForestClassifier(**best_params_rfo, random_state=42, n_jobs=-1))
])

clf_rfo_final.fit(X_temp, y_temp)

# performance of model against the test dataset
y_test_proba_rfo = clf_rfo_final.predict_proba(X_test)[:, 1]
y_test_class = (y_test_proba >= best_thresh).astype(int)

print("\nTEST METRICS:")
print("Average Precision:", average_precision_score(y_test, y_test_proba))
print("Accuracy:", accuracy_score(y_test, y_test_class))
print("ROC AUC:", roc_auc_score(y_test, y_test_proba))
print("F1 score:", f1_score(y_test, y_test_class))
print("Precision:", precision_score(y_test, y_test_class))
print("Recall:", recall_score(y_test, y_test_class))

# add metrics to table for comparison later
clf_performance['RF SMOTE'] = [average_precision_score(y_test, y_test_proba),
                               accuracy_score(y_test, y_test_class),
                               roc_auc_score(y_test, y_test_proba),
                               precision_score(y_test, y_test_class),
                               recall_score(y_test, y_test_class),
                               f1_score(y_test, y_test_class),
                               ]

# XGBoost Classifier

In [ ]:
from xgboost import XGBClassifier

#compute scale_pos_weight for imbalance (pos / neg)
pos = y_train.sum()
neg = len(y_train) - pos
scale_pos_weight = neg / pos if pos > 0 else 1.0
print("scale_pos_weight:", scale_pos_weight)

def xgboostObjective(trial):
    # paramaters to hypertune
    eval_metric = trial.suggest_categorical("eval_metric", ["logloss", "aucpr"])
    n_estimators = trial.suggest_int("n_estimators", 50, 500)
    max_depth = trial.suggest_int("max_depth", 3, 10)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 10)
    gamma = trial.suggest_int("gamma", 0, 5)
    max_delta_step = trial.suggest_int("max_delta_step", 0, 10)
    learning_rate = trial.suggest_float("learning_rate", 0.01, 0.3)
    subsample = trial.suggest_float("subsample", 0.1, 1)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.5, 1)
    reg_alpha = trial.suggest_float("reg_alpha", 0, 1)
    reg_lambda = trial.suggest_float("reg_lambda", 0, 10)

    # xgboost classifier
    clf = XGBClassifier(
        objective="binary:logistic",
        eval_metric=eval_metric,
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_child_weight=min_child_weight,
        gamma=gamma,
        max_delta_step=max_delta_step,
        learning_rate=learning_rate,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight,
    )

    # precision is the best metric for such an imbalanced dataset
    prec_score = cross_val_score(clf, X_train, y_train, cv=skf, scoring="average_precision").mean()

    return prec_score

# Utilize Optuna to obtain the best parameters
study_xgb = optuna.create_study(direction="maximize")
study_xgb.optimize(xgboostObjective, n_trials=15) #increase if have time
best_params_xgb = study_xgb.best_params

# print best parameters
print("Best hyperparameters:", best_params_xgb)
print("Best average precision:", study_xgb.best_value)

Best hyperparameters: {'eval_metric': 'aucpr', 'n_estimators': 485, 'max_depth': 4, 'min_child_weight': 5, 'gamma': 4, 'max_delta_step': 9, 'learning_rate': 0.017491036645188134, 'subsample': 0.4930384075221842, 'colsample_bytree': 0.7540646704747035, 'reg_alpha': 0.34485164426667214, 'reg_lambda': 2.7705687791842646}
Best average precision: 0.7915027500159763

In [ ]:
# refit model based on best parameters
clf_xgb = XGBClassifier(
    objective="binary:logistic",
    **best_params_xgb,
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight
)

y_train_proba = cross_val_predict(
    clf_xgb,
    X_train,
    y_train,
    cv=skf,
    method='predict_proba'
)[:, 1]

# threshold tuning based on validation set
clf_xgb.fit(X_train, y_train)
y_val_proba = clf_xgb.predict_proba(X_val)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_val, y_val_proba)
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-9)

best_thresh = thresholds[f1_scores[:-1].argmax()]
print("\nBest threshold for F1 (val set):", best_thresh)

# evalute training data with best threshold
y_train_class = (y_train_proba >= best_thresh).astype(int)

print("\nTRAIN METRICS:")
print("Average Precision:", average_precision_score(y_train, y_train_proba))
print("Accuracy:", accuracy_score(y_train, y_train_class))
print("ROC AUC:", roc_auc_score(y_train, y_train_proba))
print("F1:", f1_score(y_train, y_train_class))
print("Precision:", precision_score(y_train, y_train_class))
print("Recall:", recall_score(y_train, y_train_class))

# retrain final model based on training and validation sets
clf_xgb_final = XGBClassifier(
    objective="binary:logistic",
    **best_params_xgb,
    random_state=42,
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight
)

clf_xgb_final.fit(X_temp, y_temp)

# performance of model against the test dataset
y_test_proba_xgb = clf_xgb_final.predict_proba(X_test)[:, 1]
y_test_class = (y_test_proba >= best_thresh).astype(int)

print("\nTEST METRICS:")
print("Average Precision:", average_precision_score(y_test, y_test_proba))
print("Accuracy:", accuracy_score(y_test, y_test_class))
print("ROC AUC:", roc_auc_score(y_test, y_test_proba))
print("F1 score:", f1_score(y_test, y_test_class))
print("Precision:", precision_score(y_test, y_test_class))
print("Recall:", recall_score(y_test, y_test_class))

# add metrics to table for comparison later
clf_performance['XGBoost'] = [average_precision_score(y_test, y_test_proba),
                                    accuracy_score(y_test, y_test_class),
                                    roc_auc_score(y_test, y_test_proba),
                                    precision_score(y_test, y_test_class),
                                    recall_score(y_test, y_test_class),
                                    f1_score(y_test, y_test_class),
                                    ]

# LightGBM

In [ ]:
import lightgbm as lgb
from lightgbm import LGBMClassifier

def lightGBMObjective(trial):
    # paramaters to hypertune
    n_estimators = trial.suggest_int("n_estimators", 200, 1000)
    learning_rate = trial.suggest_float("learning_rate", 0.01, 0.1)
    num_leaves = trial.suggest_int("num_leaves", 16, 64)
    max_depth = trial.suggest_int("max_depth", 5, 15)
    min_child_samples = trial.suggest_int("min_child_samples", 20, 200)
    reg_alpha = trial.suggest_float("reg_alpha", 0, 1)
    reg_lambda = trial.suggest_float("reg_lambda", 0, 10)
    bagging_fraction = trial.suggest_float("bagging_fraction", 0.6, 0.8)
    feature_fraction = trial.suggest_float("feature_fraction", 0.6, 0.9)

    # xgboost classifier
    clf = LGBMClassifier(
        boosting_type="gbdt",
        is_unbalance=True,
        n_estimators=n_estimators,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        max_depth=max_depth,
        num_leaves=num_leaves,
        learning_rate=learning_rate,
        min_child_samples=min_child_samples,
        bagging_fraction=bagging_fraction,
        feature_fraction=feature_fraction,
        random_state=42,
        n_jobs=-1,
        verbose=-1
    )

    # precision is the best metric for such an imbalanced dataset
    prec_score = cross_val_score(clf, X_train, y_train, cv=skf, scoring="average_precision").mean()

    return prec_score

# Utilize Optuna to obtain the best parameters
study_light = optuna.create_study(direction="maximize")
study_light.optimize(lightGBMObjective, n_trials=15) #increase if have time
best_params_light = study_light.best_params

# print best parameters
print("Best hyperparameters:", best_params_light)
print("Best average precision:", study_light.best_value)

Best hyperparameters: {'n_estimators': 364, 'learning_rate': 0.05893611312728835, 'num_leaves': 59, 'max_depth': 10, 'min_child_samples': 147, 'reg_alpha': 0.4704099160904267, 'reg_lambda': 8.14374553603216, 'bagging_fraction': 0.6217880612049496, 'feature_fraction': 0.6837411588090643}
Best average precision: 0.7921886261467992

In [ ]:
# refit model based on best parameters
clf_light = LGBMClassifier(
    **best_params_light,
    random_state=42,
    n_jobs=-1
)

y_train_proba = cross_val_predict(
    clf_light,
    X_train,
    y_train,
    cv=skf,
    method='predict_proba'
)[:, 1]

# threshold tuning based on validation set
clf_light.fit(X_train, y_train)
y_val_proba = clf_light.predict_proba(X_val)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_val, y_val_proba)
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-9)

best_thresh = thresholds[f1_scores[:-1].argmax()]
print("\nBest threshold for F1 (val set):", best_thresh)

# evalute training data with best threshold
y_train_class = (y_train_proba >= best_thresh).astype(int)

print("\nTRAIN METRICS:")
print("Average Precision:", average_precision_score(y_train, y_train_proba))
print("Accuracy:", accuracy_score(y_train, y_train_class))
print("ROC AUC:", roc_auc_score(y_train, y_train_proba))
print("F1:", f1_score(y_train, y_train_class))
print("Precision:", precision_score(y_train, y_train_class))
print("Recall:", recall_score(y_train, y_train_class))

# retrain final model based on training and validation sets
clf_light_final = LGBMClassifier(
    **best_params_light,
    random_state=42,
    n_jobs=-1
)

clf_light_final.fit(X_temp, y_temp)

# performance of model against the test dataset
y_test_proba_light = clf_light_final.predict_proba(X_test)[:, 1]
y_test_class = (y_test_proba >= best_thresh).astype(int)

print("\nTEST METRICS:")
print("Average Precision:", average_precision_score(y_test, y_test_proba))
print("Accuracy:", accuracy_score(y_test, y_test_class))
print("ROC AUC:", roc_auc_score(y_test, y_test_proba))
print("F1 score:", f1_score(y_test, y_test_class))
print("Precision:", precision_score(y_test, y_test_class))
print("Recall:", recall_score(y_test, y_test_class))

# add metrics to table for comparison later
clf_performance['LightGBM'] = [average_precision_score(y_test, y_test_proba),
                               accuracy_score(y_test, y_test_class),
                               roc_auc_score(y_test, y_test_proba),
                               precision_score(y_test, y_test_class),
                               recall_score(y_test, y_test_class),
                               f1_score(y_test, y_test_class),
                               ]

# Performance Metric Comparison

In [ ]:
clf_performance.head(7)

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, average_precision_score

#y_test_proba for each model
models = {
    "Random Forest": y_test_proba_rf,
    "RF Undersampled": y_proba_rfu,
    "RF SMOTE": y_proba_rfo,
    "XGBoost": y_proba_xgb,
    #"XGB Undersampled": y_proba_xgbu,
   # "XGB SMOTE": y_proba_xgbo,
    "LightGBM": y_test_proba_light,
   # "LGBM Undersampled": y_test_proba_lightu,
   # "LGBM SMOTE": y_test_proba_lighto
}

plt.figure(figsize=(10, 8))

for name, y_proba in models.items():
    precision, recall, _ = precision_recall_curve(y_test, y_proba)
    ap = average_precision_score(y_test, y_proba)
    plt.plot(recall, precision, label=f"{name} (AP={ap:.3f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curves for All Models")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.grid(True)
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

best_clf = clf_light_final # CHANGE THIS ACCORDING TO RESULTS

y_pred_test = best_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred_test)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                              display_labels=[0, 1])
disp.plot(cmap='viridis')
plt.title('Confusion Matrix')
plt.show()

# SHAP Values

In [ ]:
import shap

explainer = shap.TreeExplainer(best_clf)
shap_values = explainer(X_test)

shap.summary_plot(shap_values, X_test)